

###### headers ######

FIND_PATH( RIGELGIS_INCLUDE_DIR MeCore/Export.h 
    PATHS
    ${RIGELGIS_DIR}/include
    $ENV{RIGELGIS_DIR}/include
    /usr/local/include
    )

    
###### libraries ######

MACRO( FIND_ME_LIBRARY MYLIBRARY MYLIBRARYNAME )
FIND_LIBRARY(${MYLIBRARY}
    NAMES
        ${MYLIBRARYNAME}
    PATHS
        ${RIGELGIS_DIR}/lib
        $ENV{RIGELGIS_DIR}/lib
        /usr/local/lib
        ${RIGELGIS_INCLUDE_DIR}/../lib
     )
ENDMACRO(FIND_ME_LIBRARY MYLIBRARY MYLIBRARYNAME)

FIND_ME_LIBRARY( RIGELGIS_MeCore_LIBRARY MeCore )
FIND_ME_LIBRARY( RIGELGIS_GUITool_LIBRARY GUITool )
FIND_ME_LIBRARY( RIGELGIS_MeDB_LIBRARY MeDB )
FIND_ME_LIBRARY( RIGELGIS_MeQt_LIBRARY MeQt )

FIND_ME_LIBRARY( RIGELGIS_MeCore_LIBRARY_DEBUG MeCored )
FIND_ME_LIBRARY( RIGELGIS_GUITool_LIBRARY_DEBUG GUIToold )
FIND_ME_LIBRARY( RIGELGIS_MeDB_LIBRARY_DEBUG MeDBd )
FIND_ME_LIBRARY( RIGELGIS_MeQt_LIBRARY_DEBUG MeQtd )


SET( RIGELGIS_FOUND "NO" )
IF( RIGELGIS_INCLUDE_DIR )
    SET( RIGELGIS_FOUND "YES" )
ENDIF( RIGELGIS_INCLUDE_DIR )
